services:
  tun2proxy:
    volumes:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv6.conf.default.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    container_name: ${TUN2PROXY_CONTAINER_NAME:-tun2proxy}
    image: ghcr.io/tun2proxy/tun2proxy-ubuntu:latest
    command: --proxy ${SOCKS5_PROXY}
    restart: always

  tntip:
    image: aron666/tntip
    container_name: ${CONTAINER_NAME:-tntip-socks5}
    environment:
      - TNT_USER=${TNT_USER}
      - TNT_PASS=${TNT_PASS}
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASS=${ADMIN_PASS:-admin}
    volumes:
      - "${DATA_DIR:-./data}:/app/UserData"
    network_mode: "service:tun2proxy"
    depends_on:
      - tun2proxy
    restart: always