services:
  tntip:
    image: aron666/tntip
    container_name: ${CONTAINER_NAME:-tntip}
    environment:
      - TNT_USER=${TNT_USER}
      - TNT_PASS=${TNT_PASS}
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASS=${ADMIN_PASS:-admin}
      - PROXY_ENABLE=${PROXY_ENABLE:-false}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASS=${PROXY_PASS}
      - SOCKS5_ENABLE=${SOCKS5_ENABLE:-false}
      - SOCKS5_PROXY=${SOCKS5_PROXY}
    ports:
      - "${TNTIP_PORT:-50010}:50010"
    volumes:
      - "${DATA_DIR:-./data}:/app/UserData"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:50010 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s